package it.capgemini.academy.giorno4.test;

public class Eccezioni {
	public static void main(String[] args) {
		//tutte le eccezioni sono nella gerarchia di Exception
		
		
		try {
			int x = 23/9;
			throw new IllegalArgumentException("male");
			//System.out.println("Istruzione non eseguita");
			//un errore di runtime blocca il flusso del programma
		} catch (ArithmeticException e) {
			System.out.println(e.getMessage());
			System.out.println(e.getCause());
			e.printStackTrace();
			
		}
		
		finally {
			System.out.println("Istruzione eseguita");

		}
		
	}

}
